version: "3"
services:
  web:
    image: gitlab/gitlab-ce:latest
    hostname: 192.168.112.232
    ports:
    - 443:443
    - 81:80
    - 33:22
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'


